stages:
  - build
  - test
  - deploy

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t webapp-dev client

test:
  stage: test
  script:
    - docker run --name temp webapp-dev npm test

deploy:
  stage: deploy
  script:
    - rm -rf /var/ww/html/
    - docker cp temp:static /var/www/html/
    - docker rm temp
    - docker image prune

build_server:
  stage: build
  script:
    - docker build -t server server